server:
  servlet:
    context-path: /identity
  port: 8080

spring:
  application:
    name: identity-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:  # Correct the spelling here
          auth: true
          starttls:
            enable: true  # Add a space after the colon
cloudinary:
  url: cloudinary://${CLOUDINARY_KEY}:${CLOUDINARY_SECRET}@${CLOUDINARY_NAME}

com:
  example:
    firebase:
      web-api-key: AIzaSyDRHtZVri40q8l3K2kXyF3kkcFQGEn6SdA
      private-key: private-key.json


