server:
  servlet:
    context-path: /brands
  port: 8082
service:
  identity-url: ${IDENTITY_SERVICE_URL}

jwt:
  secret: ${PRIVATE}

spring:
  application:
    name: brand-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
paypal-client-id: ${PAYPAL_CLIENT_ID}
paypal-client-secret: ${PAYPAL_CLIENT_SECRET}
